#ifndef ELEMENTS_H
#define ELEMENTS_H


#define   E_VIEWSETTINGS                          "viewSettings"
#define   E_VIEWSETTINGS_BTCREATEPLAYLIST         "viewSettings.btCreatePlaylist"
#define   E_VIEWSETTINGS_BTDELETEPLAYLIST         "viewSettings.btDeletePlaylist"
#define   E_VIEWSETTINGS_DPPLAYMODE               "viewSettings.dpPlayMode"
#define   E_VIEWSETTINGS_DPRIGHTMOUSEMODE         "viewSettings.dpRightMouseMode"
#define   E_VIEWSETTINGS_DPSECONDARYPLAYLIST      "viewSettings.dpSecondaryPlaylist"
#define   E_VIEWSETTINGS_LTPLAYLISTINPUT          "viewSettings.ltPlaylistInput"
#define   E_VIEWLIST                              "viewList"
#define   E_VIEWLIST_LISTSONGLIST                 "viewList.listSongList"
#define   E_VIEWLIST_LTFILTERNAME                 "viewList.ltFilterName"
#define   E_VIEWLIST_LTPLAYLIST                   "viewList.ltPlaylist"
#define   E_VIEWLIST_LTSEARCHBOX                  "viewList.ltSearchBox"
#define   E_SONGINFOVIEWB                         "songInfoViewB"
#define   E_SONGINFOVIEWB_MTSONGINFOA             "songInfoViewB.mtSongInfoA"
#define   E_VIEWSPECTRUM                          "viewSpectrum"
#define   E_VIEWSPECTRUM_SPECTRUM                 "viewSpectrum.spectrum"
#define   E_VIEWCONFIRMATION                      "viewConfirmation"
#define   E_VIEWCONFIRMATION_BTACCEPT             "viewConfirmation.btAccept"
#define   E_VIEWCONFIRMATION_BTCANCEL             "viewConfirmation.btCancel"
#define   E_VIEWCONFIRMATION_CONFIRMATIONDIALOG   "viewConfirmation.confirmationDialog"
#define   E_VIEWCONTROLS                          "viewControls"
#define   E_VIEWCONTROLS_BTNEXT                   "viewControls.btNext"
#define   E_VIEWCONTROLS_BTPAUSE                  "viewControls.btPause"
#define   E_VIEWCONTROLS_BTPLAY                   "viewControls.btPlay"
#define   E_VIEWCONTROLS_BTPREVIOUS               "viewControls.btPrevious"
#define   E_VIEWCONTROLS_SLSEEKER                 "viewControls.slSeeker"
#define   E_VIEWDIRLIST                           "viewDirList"
#define   E_VIEWDIRLIST_BTACCEPT                  "viewDirList.btAccept"
#define   E_VIEWDIRLIST_BTCANCEL                  "viewDirList.btCancel"
#define   E_VIEWDIRLIST_BTUPDIR                   "viewDirList.btUpDir"
#define   E_VIEWDIRLIST_DIVIDER                   "viewDirList.divider"
#define   E_VIEWDIRLIST_LABELINPUT                "viewDirList.labelInput"
#define   E_VIEWDIRLIST_LISTDIR                   "viewDirList.listDir"
#define   E_VIEWDIRLIST_LTINPUT                   "viewDirList.ltInput"
#define   E_VIEWMESSAGES                          "viewMessages"
#define   E_VIEWMESSAGES_LTSHOWBAR                "viewMessages.ltShowBar"
#define   E_VOLUMEVIEW                            "volumeView"
#define   E_VOLUMEVIEW_ICONVOLUME                 "volumeView.iconVolume"
#define   E_VOLUMEVIEW_SLVOLUME                   "volumeView.slVolume"
#define   E_VIEWLOG                               "viewLog"
#define   E_VIEWLOG_MTLOG                         "viewLog.mtLog"
#define   E_VIEWTOOLBAR                           "viewToolbar"
#define   E_VIEWTOOLBAR_BTADDFOLDER               "viewToolbar.btAddFolder"
#define   E_VIEWTOOLBAR_BTEXPORTPLAYLIST          "viewToolbar.btExportPlaylist"
#define   E_VIEWTOOLBAR_BTIMPORTPLAYLIST          "viewToolbar.btImportPlaylist"
#define   E_VIEWTOOLBAR_BTPINGSLAVE               "viewToolbar.btPingSlave"
#define   E_VIEWTOOLBAR_BTRESCANFOLDERS           "viewToolbar.btRescanFolders"
#define   E_VIEWTOOLBAR_BTSENDPLAYLIST            "viewToolbar.btSendPlaylist"
#define   E_SONGINFOVIEWA                         "songInfoViewA"
#define   E_SONGINFOVIEWA_MTSONGINFOA             "songInfoViewA.mtSongInfoA"


#endif// ELEMENTS_H
